### ISSUE TITLE
“睡”字编码问题

### ISSUE THREAD

**Issue by longyn** [CNMan/UnicodeCJK-WuBi#10]
U+7761,睡,htgf,htfa,htfg,

王码查询结果为：

![image](https://user-images.githubusercontent.com/5205838/70369414-f3863580-18f3-11ea-8717-e95dc22d660c.png)

**Comment by CNMan** [comment]
我不能保证86/98版和官方一致，因为码表不是我负责维护的，具体见[数据来源](https://github.com/CNMan/UnicodeCJK-WuBi/blob/master/README.md#%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%BA%90)
出现这个问题的原因有两个：
1、码表维护者弄错了
2、我整理的时候用了Excel的`VLOOKUP`函数，它选取了`排在前面`的“容错码”，而不是`排在后面`的“标准码”（有什么好办法吗？首先判断是不是容错码，再判断是不是容错码排到了标准码前面，再选取标准码而不是容错码。貌似除了人工，没法自动化操作。）

06版和官方不一致的，可以在 https://github.com/CNMan/UnicodeCJK-WuBi06/issues/1 探讨

**Comment by longyn** [comment]
我目前想找到了一系列的源（比较标准的，以王码为准），网上的一些源都有一些不准确地地方，由人工去校对，的确很花时间。我目前也在想一些自动化的操作

- 官方王码只有单字查询（验证码保护）：
- 这里有一个86, 86(18030), 98的对比表
https://www.qqxiuzi.cn/bianma/wubi.php?bm=86d18030

关于自动化的处理，我目前是这样操作的， 用python验证多个码表之间的不同，参考[这个](https://www.qqxiuzi.cn/bianma/wubi.php?bm=86d98)。最后得出不同的部分，最后人工验证。

**Comment by CNMan** [comment]
你会python？研究一下我从网上找来的这个：[wmwb2014](https://github.com/CNMan/wmwb2014)
从原始dat到csv再到其他各类码表的转换

这个是C语言版的 https://github.com/lifenjoiner/wmwb_dat2csv ，兼容了2018版，你看看能不能移植到python上:)

**Comment by longyn** [comment]
可以，等我有空的时候研究一下。
