### ISSUE TITLE
请教笔顺问题

### ISSUE THREAD

**Issue by nobodxbodon** [CNMan/UnicodeCJK-WuBi#11]
请问笔顺的 12345 是对应`KangxiRadicals.txt`的行号吗？
如果是的话，`CJK.txt`中的：
```
U+4E01,丁,sgh,sgh,sgh,12,15
```
大陆笔顺为何最后一笔是 2：`U+2F01,⼁`
而不是 6 呢？`U+2F05,⼅`

**Comment by nobodxbodon** [comment]
不好意思刚领会到，应该是`CJK.txt`中的这几个吧？
```
U+4E00,一,ggll,ggll,ggll,1,1

U+4E28,丨,hhll,hhll,hhll,2,2
U+4E85,亅,hhll,hhll,hhll,2,5

U+4E3F,丿,ttll,ttll,ttll,3,3

U+4E36,丶,yyll,yyll,yyll,4,4
U+4E40,乀,yyll,tyi,yyll,4,5
U+4E41,乁,yyll,gyi,yyll,4,5

U+4E59,乙,nnll,nnll,nnll,5,5
U+4E5A,乚,nnll,nnll,nnll,5,5
U+4E5B,乛,nnll,nnll,nnll,5,5
```
也许最好在 README 说明一下？

**Comment by nobodxbodon** [comment]
@CNMan 报告一下
基于本库数据发布了个汉字笔顺 npm 库：https://github.com/program-in-chinese/npm-chinese-character-strokes 如有不妥请告知。

**Comment by CNMan** [comment]
@nobodxbodon 12345代表橫、豎、撇、捺（點）、折

**Comment by nobodxbodon** [comment]
@CNMan 多谢确认。已更新 repo 中的[说明](https://github.com/program-in-chinese/npm-chinese-character-strokes#%E5%8A%9F%E8%83%BD)，下一版发布时会更新 npm 库。
