### ISSUE TITLE
再打听一下，关于汉字部件构成信息，请问知道哪儿有整理好的数据吗？比如：团=口+才

### ISSUE THREAD

**Issue by nobodxbodon** [CNMan/UnicodeCJK-WuBi#12]
地=土+也，群=君+羊，冷=冫（bing）+令，望=亡+月+王，等等？覆盖常用字即可。

贴吧也问了：
https://tieba.baidu.com/p/6800196908

**Comment by CNMan** [comment]
https://github.com/cjkvi/cjkvi-ids

**Comment by nobodxbodon** [comment]
多谢. 忘说了, 之前已有位告知了这个数据源:
http://git.chise.org/gitweb/?p=chise/ids.git;a=blob_plain;f=IDS-UCS-Basic.txt;hb=HEAD
感觉挺好用

**Comment by nobodxbodon** [comment]
刚发现 cjkvi-ids 的常用字部分也是基于 chise 的数据：
> 'ids.txt' is derived from CHISE project. 

在贴吧里帖子 14 楼提到了《信息处理用GB13000.1字符集汉字部件规范》，还在查有没有基于这个规范的拆字数据源。。
