### ISSUE TITLE
有个别字的86五笔编码疑似有误

### ISSUE THREAD

**Issue by SyzygyYuan** [CNMan/UnicodeCJK-WuBi#14]
由于我只关心86五笔的编码，从文本数据中提出86五笔编码数据后，发现有如下项的编码疑似有误。
```
伳	trff
卵	lhng
哖	ipbf
嘅	gghg
娮	llb
孳	gcff
寧	pgng
悋	ktuf
枰	gudn
栻	eeee
烒	eeee
熂	oooo
盁	pyfg
秥	ipbf
紎	thd
絕	dggg
缌	sawp
翴	glfl
迎	pyfg
鄓	ahnl
酿	pfiu
鈌	hhgg
镙	ffff
韘	jjjj
魫	jvtk
龺	fjh	应为fjj
鿹	qpnm	应为qgpm
鿺	gqqg	一般麦是gt，容错码？
```

**Comment by CNMan** [comment]
86版数据来源多样，不是我编码的，也不保证正确，有可能是错码、简码、容错码...
建议下载[CPC中文印刷社区](http://www.cnprint.org/)的[黄狗五笔超大字符集版](http://www.cnprint.org/bbs/thread/197/328367/)导出码表校对并反馈更新，这里的数据只是用来参考编码06版的。
